import puppeteer from 'file:///C:/Users/Pushkar/AppData/Local/Temp/claude/C--Users-Pushkar-Documents-GitHub-mappingg/6f89b206-8f2a-481c-ae40-4711581c1bae/scratchpad/pt/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js';
import pg from 'pg';
const url = new URL(process.env.DATABASE_URL); url.searchParams.delete('sslmode');
const pool = new pg.Pool({ connectionString: url.toString(), ssl: { rejectUnauthorized: false } });
const q = async (s, a) => (await pool.query(s, a)).rows;
const before = (await q('select count(*)::int n from site_events'))[0].n;
const start = new Date();
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', protocolTimeout: 120000 });
const p = await b.newPage(); await p.setViewport({ width: 1366, height: 900 });
await p.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36 MgDeployCheck');
await p.goto('https://www.mappingg.com/blog?utm_source=deploycheck', { waitUntil: 'networkidle2', timeout: 120000 });
await new Promise(r => setTimeout(r, 6000));
await b.close();
const mine = await q("select kind, path, source, device from site_events where at >= $1 and source = 'deploycheck'", [start]);
console.log('events before:', before, '| my live test visit recorded:', JSON.stringify(mine));
console.log('real visitor events since deploy (not mine):', (await q("select count(*)::int n from site_events where coalesce(source,'') <> 'deploycheck'"))[0].n);
const vids = (await q("select distinct vid from site_events where source = 'deploycheck'")).map(r => r.vid);
const d = await pool.query('delete from site_events where vid = any($1)', [vids]);
console.log('removed my test events:', d.rowCount);
await pool.end();
